/*
 * RunescapeOptions.java
 *
 * Created on September 4, 2003, 9:11 PM
 */

/**
 *
 * @author  harperart
 */
public class RunescapeOptions extends javax.swing.JDialog
{
    
    /** Creates new form RunescapeOptions */
    public RunescapeOptions(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        prefs = java.util.prefs.Preferences.userNodeForPackage(RunescapeOptions.class);
        initComponents();
        getRootPane().setDefaultButton(GoButton);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        autoLoginCheckBox = new javax.swing.JCheckBox();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        maskPasswordCheckBox = new javax.swing.JCheckBox();
        GoButton = new javax.swing.JButton();
        noAutoLogoutCheckBox = new javax.swing.JCheckBox();
        worldSelector = new javax.swing.JComboBox();
        authNameLabel = new javax.swing.JLabel();
        authUserNameLabel = new javax.swing.JLabel();
        authPasswordLabel = new javax.swing.JLabel();
        authUserNameTextField = new javax.swing.JTextField();
        authPasswordField = new javax.swing.JPasswordField();
        runescapeTextLabel = new javax.swing.JLabel();
        autoLoginCheckbox = new javax.swing.JCheckBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Runescape Prefs");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        autoLoginCheckBox.setSelected(prefs.getBoolean("autoLogin",false));
        autoLoginCheckBox.setText("Auto Login");
        autoLoginCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                autoLoginCheckBoxActionPerformed(evt);
            }
        });

        getContentPane().add(autoLoginCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        userNameTextField.setText(prefs.get("userName","userName"));
        userNameTextField.setEnabled(false);
        userNameTextField.setEnabled(autoLoginCheckBox.isSelected());
        userNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                userNameTextFieldActionPerformed(evt);
            }
        });

        getContentPane().add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, -1));

        passwordField.setText(prefs.get("password",""));
        passwordField.setEnabled(false);
        passwordField.setEnabled(autoLoginCheckBox.isSelected());
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, -1));

        jLabel1.setText("userName");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 60, -1));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveButtonActionPerformed(evt);
            }
        });

        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        maskPasswordCheckBox.setSelected(true);
        maskPasswordCheckBox.setText("Mask password");
        maskPasswordCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                maskPasswordCheckBoxActionPerformed(evt);
            }
        });

        getContentPane().add(maskPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        GoButton.setText("Go");
        GoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GoButtonActionPerformed(evt);
            }
        });

        getContentPane().add(GoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        noAutoLogoutCheckBox.setSelected(true);
        noAutoLogoutCheckBox.setSelected(prefs.getBoolean("noTimeout",true));
        noAutoLogoutCheckBox.setText("No auto logout");
        noAutoLogoutCheckBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                noAutoLogoutCheckBoxActionPerformed(evt);
            }
        });

        getContentPane().add(noAutoLogoutCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        worldSelector.setModel(getWorlds());
        worldSelector.setSelectedIndex(0);
        worldSelectorActionPerformed(null);
        worldSelector.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                worldSelectorActionPerformed(evt);
            }
        });

        getContentPane().add(worldSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 230, -1));

        authNameLabel.setText("Authentication");
        getContentPane().add(authNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        authUserNameLabel.setText("userName");
        getContentPane().add(authUserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        authPasswordLabel.setText("password");
        getContentPane().add(authPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        authUserNameTextField.setText(prefs.get("authName",""));
        getContentPane().add(authUserNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));

        authPasswordField.setText(prefs.get("authPassword",""));
        authPasswordField.setEchoChar('\u225d');
        getContentPane().add(authPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, -1));

        runescapeTextLabel.setText("Runescape");
        getContentPane().add(runescapeTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));

        autoLoginCheckbox.setSelected(true);
        autoLoginCheckbox.setText("Auto relogin");
        getContentPane().add(autoLoginCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        pack();
    }//GEN-END:initComponents

    private void worldSelectorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_worldSelectorActionPerformed
    {//GEN-HEADEREND:event_worldSelectorActionPerformed

    }//GEN-LAST:event_worldSelectorActionPerformed

    private void noAutoLogoutCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noAutoLogoutCheckBoxActionPerformed
    {//GEN-HEADEREND:event_noAutoLogoutCheckBoxActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_noAutoLogoutCheckBoxActionPerformed

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GoButtonActionPerformed
    {//GEN-HEADEREND:event_GoButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_GoButtonActionPerformed

    private void maskPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_maskPasswordCheckBoxActionPerformed
    {//GEN-HEADEREND:event_maskPasswordCheckBoxActionPerformed
        if(maskPasswordCheckBox.isSelected())
            passwordField.setEchoChar('*');
        else
            passwordField.setEchoChar('\0');
    }//GEN-LAST:event_maskPasswordCheckBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
    {//GEN-HEADEREND:event_saveButtonActionPerformed
        prefs.putBoolean("autoLogin", autoLoginCheckBox.isSelected());
        prefs.put("userName", userNameTextField.getText());
        prefs.put("password", new String(passwordField.getPassword()));
        prefs.putBoolean("noTimeout", isNoTimeout());
        prefs.put("authName", authUserNameTextField.getText());
        prefs.put("authPassword", new String(authPasswordField.getPassword()));
        try
        {
            prefs.flush();
            javax.swing.JOptionPane.showMessageDialog(this,"Preferences saved");
        }
        catch(java.util.prefs.BackingStoreException e)
        {
            javax.swing.JOptionPane.showInternalMessageDialog(this,"Could not save prefs!","Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void autoLoginCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_autoLoginCheckBoxActionPerformed
    {//GEN-HEADEREND:event_autoLoginCheckBoxActionPerformed
        userNameTextField.setEnabled(autoLoginCheckBox.isSelected());
        passwordField.setEnabled(autoLoginCheckBox.isSelected());
    }//GEN-LAST:event_autoLoginCheckBoxActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_userNameTextFieldActionPerformed
    {//GEN-HEADEREND:event_userNameTextFieldActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        setVisible(false);
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new RunescapeOptions(new javax.swing.JFrame(), true).show();
    }
    public Object getSelectedWorld()
    {
        return worldSelector.getSelectedItem();
    }
    public String getUserName()
    {
        return userNameTextField.getText();
    }    
    
    public String getPassword()
    {
        return new String(passwordField.getPassword());
    }
    
    public boolean isAutoLogin()
    {
        return autoLoginCheckBox.isSelected();
    }
    
    public boolean isNoTimeout()
    {
        return noAutoLogoutCheckBox.isSelected();
    }
    
    public javax.swing.DefaultComboBoxModel getWorlds()
    {
        return worlds;
    }
    public String getAuthName()
    {
        return authUserNameTextField.getText();
    }
    public String getAuthPassword()
    {
        return new String(authPasswordField.getPassword());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoButton;
    private javax.swing.JLabel authNameLabel;
    private javax.swing.JPasswordField authPasswordField;
    private javax.swing.JLabel authPasswordLabel;
    private javax.swing.JLabel authUserNameLabel;
    private javax.swing.JTextField authUserNameTextField;
    private javax.swing.JCheckBox autoLoginCheckBox;
    private javax.swing.JCheckBox autoLoginCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox maskPasswordCheckBox;
    private javax.swing.JCheckBox noAutoLogoutCheckBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel runescapeTextLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JComboBox worldSelector;
    // End of variables declaration//GEN-END:variables

    private java.util.prefs.Preferences prefs;    
    
    private  javax.swing.DefaultComboBoxModel worlds = 
    new javax.swing.DefaultComboBoxModel(new String[]{
        Main.world1,
        Main.world2,
        Main.world3,
        Main.world5,
        Main.world6,
        Main.world7,
        Main.world8,
        Main.world9,
        Main.world10,
        Main.world11,
        Main.world12,
        Main.world13,
        Main.world14,
        Main.world15,
        Main.world16,
        Main.world17,
        Main.world18,
        Main.world19,
        Main.world20,
        Main.worldL,
        Main.worldLM});
    
}
